### ISSUE TITLE
不能使用vec模式

### ISSUE THREAD

**Issue by SizheRee** [ofooo/FAQrobot#1]
你好。
我尝试了一下你的模型，感觉很好。
就是ｖｅｃ模式模型加载出错了。

>问答知识库开始载入
正在载入词向量
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ree/workspace/easy-exprossion/modules/DL/FAQrobot/similarity.py", line 100, in __init__
    self.reload()
  File "/home/ree/workspace/easy-exprossion/modules/DL/FAQrobot/similarity.py", line 134, in reload
    self.vecModel = Word2Vec.load(pp('./pack/Word60.model'))
  File "/home/lsz/.virtualenvs/python3.5/lib/python3.5/site-packages/gensim/models/word2vec.py", line 1396, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/home/lsz/.virtualenvs/python3.5/lib/python3.5/site-packages/gensim/utils.py", line 272, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/home/lsz/.virtualenvs/python3.5/lib/python3.5/site-packages/gensim/models/word2vec.py", line 1420, in _load_specials
    super(Word2Vec, self)._load_specials(*args, **kwargs)
  File "/home/lsz/.virtualenvs/python3.5/lib/python3.5/site-packages/gensim/utils.py", line 302, in _load_specials
    val = np.load(subname(fname, attrib), mmap_mode=mmap)
  File "/home/lsz/.virtualenvs/python3.5/lib/python3.5/site-packages/numpy/lib/npyio.py", line 419, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/lsz/.virtualenvs/python3.5/lib/python3.5/site-packages/numpy/lib/format.py", line 681, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 27787244 into shape (574288,60)

**Comment by ofooo** [comment]
你要下载我备注里面放的百度云 里的文件，是我训练的词向量文件。放在同一个文件夹里面就可以了。
